# Generated by Django 4.2.13 on 2024-05-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="core.post",
        ),
    ]
