# Generated by Django 4.2.13 on 2024-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0002_user_avatar_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
