# Generated by Django 4.2.13 on 2024-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0003_alter_user_created_alter_user_updated"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="core.user",
        ),
    ]
