# Generated by Django 4.2.13 on 2024-05-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="core_user",
        ),
    ]
